# Generated by Django 5.2.8 on 2025-11-27 12:30

import datetime
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='chat id')),
                ('data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('daily_goal_ml', models.IntegerField(default=3000, help_text='Your total water goal for the day (in milliliters). The bot will help you reach this amount before the end of your reminder window. Default is 3000 ml.', verbose_name='daily goal (ml)')),
                ('reminder_window_start', models.TimeField(default=datetime.time(8, 0), help_text='The time of day when your reminders should begin. Default is 08:00.', verbose_name='first reminder')),
                ('reminder_window_end', models.TimeField(default=datetime.time(22, 0), help_text='The time of day when your reminders should stop. The final reminder will never be sent after this time. Default is 22:00.', verbose_name='last reminder')),
                ('consumption_size_ml', models.IntegerField(default=250, help_text='How much water you usually drink per reminder (in milliliters). This must be between 100 and 500 ml. The bot uses this to plan how many reminders you need each day. Default is 250 ml.', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(500)], verbose_name='consumption size (ml)')),
                ('default_postpone_seconds', models.IntegerField(default=900, help_text='How long a reminder should be postponed when you choose "Remind me later" (in seconds). Default is 15 minutes (900 seconds). ', verbose_name='default postpone (seconds)')),
                ('minimum_interval_seconds', models.FloatField(default=1200.0, help_text='The shortest allowed time between reminders (in seconds). This prevents the bot from sending reminders too close together. Default is 20 minutes (1200 seconds).', verbose_name='minimum interval (seconds)')),
                ('reminder_text', models.CharField(default='Time to hydrate!', help_text="The message you want the bot to send you for each reminder. Default is 'Time to hydrate!'.", verbose_name='reminder text')),
                ('next_reminder_at', models.TimeField(blank=True, help_text='when the next reminder is scheduled', null=True, verbose_name='next reminder at')),
                ('consumed_today_ml', models.IntegerField(default=0, help_text='amount of water consumed today (ml), resets at midnight', verbose_name='consumed today (ml)')),
                ('is_initialized', models.BooleanField(default=False, help_text='whether the initial setup has been completed', verbose_name='is initialized')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
