# Generated by Django 5.2.8 on 2025-11-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsettings',
            name='default_postpone_seconds',
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='timestamp of the last reminder sent', null=True, verbose_name='last reminder sent at'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='reminder_repeat_interval_seconds',
            field=models.IntegerField(default=900, help_text="How long the bot should wait before repeating a reminder if you haven't logged your drink (in seconds). Default is 15 minutes (900 seconds). ", verbose_name='reminder repeat interval (seconds)'),
        ),
    ]
