# Generated by Django 5.2.8 on 2025-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_remove_telegramsettings_default_postpone_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsettings',
            name='reminder_repeat_interval_seconds',
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='last_reminder_sent_at',
            field=models.TimeField(blank=True, help_text='time of the last reminder sent', null=True, verbose_name='last reminder sent at'),
        ),
    ]
