# Generated by Django 5.2.8 on 2025-11-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_remove_telegramsettings_reminder_repeat_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='next_overview_at',
            field=models.TimeField(blank=True, help_text='when the next daily overview is scheduled', null=True, verbose_name='next overview at'),
        ),
    ]
