# Generated by Django 5.2.8 on 2025-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_telegramsettings_next_overview_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='timezone',
            field=models.CharField(default='Europe/Brussels', help_text="the user's timezone, e.g., 'Europe/Brussels'", max_length=64, verbose_name='timezone'),
        ),
    ]
